name: "Update component CSV"
on:
  schedule:
    - cron: '0 4 * * *'
  push:
  workflow_dispatch:
jobs:
  build_and_update:
    name: "Update CSV and upload"
    runs-on: ubuntu-20.04
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip wget zip unzip p7zip-full
          sudo pip3 install requests
      - name: Download DB and generate CSV
        run: |
          rm -rf web
          mkdir web
          #cd web
          #BASEURL=https://yaqwsx.github.io/jlcparts/data/cache
          #wget -q ${BASEURL}.zip
          #for seq in $(seq 1 9); do
          #    wget -q ${BASEURL}.z0$seq || true
          #done
          #rm -f cache.sqlite3
          #7z x cache.zip

          #python3 ../gencsv.py cache.sqlite3 parts.csv.xz
          #rm -f cache.z?? cache.sqlite3
          echo foo | xz>web/parts.csv.xz
      - name: Upload CSV
        uses: actions/upload-pages-artifact@v1
        with:
          name: CSV
          path: web
          retention-days: 14
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_and_update
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
